services:
  # PostgreSQL Database
  db:
    image: postgres:15-alpine
    container_name: crop_project
    environment:
      POSTGRES_DB: crop_app
      POSTGRES_USER: admin_crop
      POSTGRES_PASSWORD: mesy
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin_crop -d crop_app"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - crop_network

  # Django Backend
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: crop_monitoring_web
    command: /app/scripts/start.sh
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/mediafiles
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - SECRET_KEY=django-insecure-3b5+u*=a(70!ve)023wf8^yw7^w8ksm1(yst5dc(-fk7b9z%9r
      - DB_NAME=crop_app
      - DB_USER=admin_crop
      - DB_PASSWORD=mesy
      - DB_HOST=db
      - DB_PORT=5432
      - ALLOWED_HOSTS=localhost,127.0.0.1,0.0.0.0
    depends_on:
      db:
        condition: service_healthy
    networks:
      - crop_network

volumes:
  postgres_data:
  static_volume:
  media_volume:

networks:
  crop_network:
    driver: bridge